apiVersion: v1
kind: Service
metadata:
  name: preview
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.path: /
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: preview